name: Deploy React App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          VITE_OPENAI_API_KEY: ${{ secrets.VITE_OPENAI_API_KEY }}
          VITE_GOOGLE_API_KEY: ${{ secrets.VITE_GOOGLE_API_KEY }}
          VITE_GOOGLE_CX: ${{ secrets.VITE_GOOGLE_CX }}
          VITE_OPENAI_ASSISTANT_ID: ${{ secrets.VITE_OPENAI_ASSISTANT_ID }}
          VITE_RESEARCH_EMAIL_API_KEY: ${{ secrets.VITE_RESEARCH_EMAIL_API_KEY }}
          VITE_RESEARCH_EMAIL_ASSISTANT_ID: ${{ secrets.VITE_RESEARCH_EMAIL_ASSISTANT_ID }}

      - name: List build output
        run: ls -la dist/

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages